### ISSUE TITLE
Update the Source Code of http://hn.premii.com/#/ 

### ISSUE THREAD

**Issue by titoBouzout** [premii/hn#12]
Please dump the source code of that page somewhere so we can fix it. Thanks

**Comment by zachberger** [comment]
+1

**Comment by fubar-coder** [comment]
:+1:

**Comment by gblazex** [comment]
+1

**Comment by niutech** [comment]
Have a look at the source of http://hn.premii.com/ and http://hn.premii.com/resource/hn_3.05.js using JS beautifier.
