### ISSUE TITLE
Web pages open in Safari, not Safari View Controller

### ISSUE THREAD

**Issue by craigbox** [premii/hn#25]
Since the update on 2018-01-05, web views no longer open in Safari View Controller.

Tap on an article
Tap on the URL at the top
Expected: opens Safari View Controller with web view
Actual: switches to Safari and opens link there

**Comment by jsjohnst** [comment]
Even worse than articles loading in Safari, the HN discussion threads now load in Safari too. While I appreciate the iPhone X support in this release, it’s otherwise such a step backwards I’m planning to downgrade.

**Comment by craigbox** [comment]
Ok, that's fixed in the latest build, but the orange really doesn't work for me when you have color content on the page.  Could we revert back to the system default accents?
